name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize]

env:
  NEXT_PUBLIC_BASE_SEPOLIA: ${{ secrets.NEXT_PUBLIC_BASE_SEPOLIA }}
  NEXT_PUBLIC_E2E_TEST_ENABLED: "true"

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Set up foundry (includes anvil)
      uses: foundry-rs/foundry-toolchain@v1
    - name: Start anvil fork in base sepolia
      run: anvil --fork-url "${{ env.NEXT_PUBLIC_BASE_SEPOLIA || 'https://sepolia.base.org' }}" --port 8545 &
    - name: Warm up anvil
      run: npm run warmup:anvil
    - name: Build application
      run: npm run build:turbo
    - name: Install Playwright Browsers
      run: npm run playwright:install:chromium # CI only tests in chromium
    - name: Run Playwright tests
      run: npm run test:e2e
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
