name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Set up foundry (includes anvil)
      uses: foundry-rs/foundry-toolchain@v1
    - name: Start anvil fork in base sepolia
      run: anvil --fork-url "https://sepolia.base.org" --port 8545 &
    - name: Install Playwright Browsers
      run: npm run playwright:install:chromium # CI only tests in chromium
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
